[package]
name = "chainql-core"
description = "Jrsonnet library for chainql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
frame-metadata.workspace = true
tokio.workspace = true
jrsonnet-evaluator.workspace = true
jrsonnet-gcmodule.workspace = true
hex = "0.4.3"
jsonrpsee = { version = "0.23.1", features = ["macros", "ws-client"] }
parity-scale-codec = { version = "3.6.12", features = ["derive"] }
scale-info = "2.11.3"
serde = "1.0.203"
serde_json = "1.0.117"
thiserror = "1.0.61"
num-bigint = "0.4.5"
cumulus-primitives-proof-size-hostfunction = "0.8.0"
sp-io = "36.0.0"
sp-core = { version = "33.0.1", default-features = false, features = ["std"] }
sc-executor = "0.38.0"
sp-state-machine = "0.41.0"
hyper = "1.3.1"
http = "1.1.0"
libsecp256k1 = "0.7.1"
sp-runtime = "37.0.0"
directories = "5.0.1"
tracing = { version = "0.1.41", optional = true }
log = { version = "0.4.24", optional = true }

[features]
default = ["log-tracing"]
log-tracing = ["dep:tracing"]
log = ["dep:log"]