[package]
name = "chainql-core"
description = "Jrsonnet library for chainql"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
frame-metadata.workspace = true
tokio.workspace = true
jrsonnet-evaluator.workspace = true
jrsonnet-gcmodule.workspace = true
hex = "0.4.3"
jsonrpsee = { version = "0.18.1", features = ["macros", "ws-client"] }
parity-scale-codec = { version = "3.1.5", features = ["derive"] }
scale-info = "2.1.2"
serde = "1.0.101"
serde_json = "1.0.87"
sp-core = {version = "21.0.0", default-features = false, features = ["std"] }
thiserror = "1.0.31"
peg = "0.8.0"
num-traits = "0.2.15"
num-bigint = "0.4.3"
