[package]
name = "chainql"
description = "Query substrate chains using jsonnet"
license = "MIT"
version = "0.4.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
frame-metadata = { version = "15.0.0", package = "chainql-frame-metadata", path = "./frame-metadata/frame-metadata" }
hex = "0.4.3"
jrsonnet-evaluator = { version = "0.5.0-pre9", features = ["exp-destruct", "exp-bigint"] }
jrsonnet-stdlib = { version = "0.5.0-pre9", features = ["exp-bigint"] }
jrsonnet-cli = { version = "0.5.0-pre9", features = ["exp-bigint"] }
jrsonnet-gcmodule = "0.3.4"
jsonrpsee = { version = "0.18.1", features = ["macros", "ws-client"] }
parity-scale-codec = { version = "3.1.5", features = ["derive"] }
scale-info = "2.1.2"
serde = "1.0.101"
serde_json = "1.0.87"
sp-core = {version = "11.0.0", default-features = false, features = ["std"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
thiserror = "1.0.31"
peg = "0.8.0"
num-traits = "0.2.15"
num-bigint = "0.4.3"
